### ISSUE TITLE
Stupid question, but how do I get this to run?

### ISSUE THREAD

**Issue by mslav** [TimboKZ/redux-calculator#1]

**Comment by TimboKZ** [comment]
I'm afraid this repo is ancient history now, I don't think I ever got the calculator working. I also now prefer plain ES6 over TypeScript since I mostly do Node backend dev.

I should've probably created a better README because I can't recall all of the steps now... I think you can run `webpack watch` (or `--watch`, was it?) and code away. As said above, the calculator isn't quite working so you will have to fix that.
